export const ApiPath = {
  auth: '/auth',
  register: '/register',
  authenticate: '/authenticate',
  forgot_password: '/forgot-password',
  reset_password: '/reset-password',
  confirm_email: '/confirm-email',
  logout: '/logout',
  users: '/users',
  pupils: '/pupils',
  pupil: '/pupil',
  classes: '/classes',
  student: '/student',
  students: '/students',
  teacher: '/teacher',
  teachers: '/teachers',
  admin: '/admin',
  booked_classes: '/booked_classes',
  book_class: '/book_class',
  browse_classes: '/browse_classes',
  subscription: '/subscription',
  total_numbers: '/total_numbers',
};
